baseURL: https://ma-paroisse.ch/
title: ma-paroisse.ch

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
copyright: CC0 (domaine public)
cleandestinationdir: true
removePathAccents: true

build:
  noJSConfigInAssets: true
  writeStats: false

disableKinds:
  - RSS
  - taxonomy
  - term
  - 404

outputs:
  home:
    - html
    - json
  section:
    - html
    - json
  page:
    - html

params:
  
  author:
    name: Nicolas Friedli
    email: nicolas.friedli+mp@gmail.com
  
  footer: |  

    [Plan complet](/sitemap/) / [GitHub](https://github.com/nfriedli/ma-paroisse.ch)

    Responsable: [Nicolas Friedli](https://nicolasfriedli.ch/)