minify:
  minifyOutput: true
  tdewolff:
    html:
      keepQuotes: false
      keepDefaultAttrVals: false
      keepWhitespace: false
    js:
      keepVarNames: false
      precision: 0
    json:
      keepNumbers: true
