minify:
  minifyOutput: true
  tdewolff:
    html:
      keepQuotes: true
      keepDefaultAttrVals: false
      keepWhitespace: true
    js:
      keepVarNames: false
      precision: 0
    json:
      keepNumbers: true
