# googleAnalytics: UA-59198139-6

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepQuotes: true
      keepDefaultAttrVals: false

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true